import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ClerkProvider,
} from '@clerk/nextjs'

import "./globals.css";
import { CSPostHogProvider } from './providers'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MealFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <ClerkProvider>
    <html lang='en'>
    <CSPostHogProvider>
      <body>
        {children}
      </body>
    </CSPostHogProvider>
    </html>
  </ClerkProvider>
);
}
